import { ProductGender } from "@prisma/client";

export const BRANDS_TO_CONFIRM = [
  { name: "Clarks", description: "British shoemaking heritage renowned for premium leather oxfords, brogues, and classic boots." },
  { name: "Aldo", description: "International fashion footwear specializing in modern heels, pumps, evening sandals, and chic flats." },
  { name: "Timberland", description: "Rugged outdoor lifestyle brand celebrated for waterproof boots, chukkas, and hiking footwear." },
  { name: "Bata", description: "Trusted global footwear brand known for quality school shoes, durable daily wear, and comfortable sandals." },
  { name: "Hush Puppies", description: "Comfort-first footwear brand crafting lightweight formal loafers, dress shoes, and casual walking shoes." },
  { name: "Steve Madden", description: "Trendsetting footwear designer famous for statement heels, block pumps, ankle boots, and fashion mules." },
  { name: "Vans", description: "Iconic Southern California skate and lifestyle brand famous for classic canvas low-tops and slip-ons." },
  { name: "Converse", description: "Historic American footwear brand celebrated for timeless Chuck Taylor canvas sneakers and high-tops." },
  { name: "Nike", description: "Global leader in athletic footwear and innovation." },
  { name: "Adidas", description: "Pioneering sport and lifestyle footwear brand." },
  { name: "Puma", description: "Performance athletic and speed-inspired lifestyle footwear." },
  { name: "New Balance", description: "Ergonomic running and lifestyle footwear heritage." },
  { name: "Reebok", description: "Classic fitness, cross-training, and gym footwear." },
  { name: "Skechers", description: "Comfort-focused footwear with arch support and memory foam." },
  { name: "ASICS", description: "Japanese precision running and court stability footwear." },
];

export const CATEGORIES_TO_CONFIRM = [
  { name: "Men", description: "Men's formal, casual, boots, and lifestyle footwear" },
  { name: "Women", description: "Women's heels, flats, boots, casual, and comfort footwear" },
  { name: "Sports", description: "Performance athletic, running, football, training, and court footwear" },
];

const IMAGES = {
  formalMenOxford: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=800&auto=format&fit=crop",
  formalMenBrogue: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=800&auto=format&fit=crop",
  menLoafer: "https://images.unsplash.com/photo-1582895181515-56f8f53c9e37?q=80&w=800&auto=format&fit=crop",
  menChelseaBoot: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=800&auto=format&fit=crop",
  menHikingBoot: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=800&auto=format&fit=crop",
  menCasualSneaker: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=800&auto=format&fit=crop",
  menSlipOn: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop",
  menSandals: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=800&auto=format&fit=crop",

  womenHeelsStiletto: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop",
  womenHeelsBlock: "https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800&auto=format&fit=crop",
  womenHeelsPlatform: "https://images.unsplash.com/photo-1581101767113-1677fc2beaa8?q=80&w=800&auto=format&fit=crop",
  womenFlatsBallet: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop",
  womenFlatsMules: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?q=80&w=800&auto=format&fit=crop",
  womenSandalsHeeled: "https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=800&auto=format&fit=crop",
  womenBootsAnkle: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop",
  womenBootsChelsea: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=800&auto=format&fit=crop",
  womenCasualSneaker: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop",
  womenWalkingShoe: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=800&auto=format&fit=crop",

  sportsRunning: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop",
  sportsTrailRunning: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?q=80&w=800&auto=format&fit=crop",
  sportsFootball: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=800&auto=format&fit=crop",
  sportsBasketball: "https://images.unsplash.com/photo-1579338559194-a162d19bf842?q=80&w=800&auto=format&fit=crop",
  sportsTennis: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?q=80&w=800&auto=format&fit=crop",
  sportsGymTraining: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=800&auto=format&fit=crop",
  sportsSlides: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=800&auto=format&fit=crop",

  kidsSchoolBoys: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=800&auto=format&fit=crop",
  kidsSchoolGirls: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop",
  kidsSneakers: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?q=80&w=800&auto=format&fit=crop",
  kidsSports: "https://images.unsplash.com/photo-1588117305388-c2631a279f82?q=80&w=800&auto=format&fit=crop",
};

export interface SeedItem {
  productCode: string;
  name: string;
  brandName: string;
  categoryName: "Men" | "Women" | "Sports";
  gender: ProductGender;
  basePrice: number;
  salePrice: number | null;
  isNew?: boolean;
  isFeatured?: boolean;
  description: string;
  imageUrl: string;
  sizes: number[];
  colors: string[];
  stockOverride?: Record<number, number>;
}

export const EXPANDED_PRODUCTS_DATA: SeedItem[] = [
  // 1. MEN'S FORMAL, BUSINESS, BOOTS & CASUAL
  {
    productCode: "CL-051",
    name: "Clarks Whiddon Cap Leather Oxford",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 21500,
    salePrice: 18900,
    isFeatured: true,
    description: "Classic men's cap-toe Oxford dress shoe crafted from full-grain black leather. Features an Ortholite footbed with soft textile lining for boardroom and formal office elegance.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "Dark Brown"],
  },
  {
    productCode: "CL-052",
    name: "Clarks Oliver Wingtip Derby Brogue",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 24500,
    salePrice: null,
    isNew: true,
    description: "Sophisticated men's wingtip brogue derby with handcrafted perforation details. Engineered with a durable leather sole and cushioned arch support for business suits and formal events.",
    imageUrl: IMAGES.formalMenBrogue,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Tan", "Cognac", "Black"],
  },
  {
    productCode: "CL-053",
    name: "Clarks Howard Edge Plain Toe Derby",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 19800,
    salePrice: 16500,
    description: "Timeless plain-toe formal derby shoe in polished dark leather. Provides a flexible rubber outsole and hidden elasticated goring for all-day office comfort.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [39, 40, 41, 42, 43],
    colors: ["Black", "Mahogany"],
  },
  {
    productCode: "HP-054",
    name: "Hush Puppies Bennett Leather Penny Loafer",
    brandName: "Hush Puppies",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 17500,
    salePrice: 14900,
    isFeatured: true,
    description: "Refined men's penny loafer made from supple burnished leather. Equipped with Bounce Plus footbed technology for superior shock absorption during extended office hours and meetings.",
    imageUrl: IMAGES.menLoafer,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "Burgundy", "Tan"],
  },
  {
    productCode: "HP-055",
    name: "Hush Puppies Detroit Monk Strap Dress Shoe",
    brandName: "Hush Puppies",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 22000,
    salePrice: null,
    description: "Elegant single-buckle monk strap formal shoe in rich smooth leather. Pairs perfectly with tailored suits and formal dinner wear, featuring breathable leather linings.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black", "Dark Brown"],
  },
  {
    productCode: "BT-056",
    name: "Bata Executive Classic Oxford",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 8500,
    salePrice: 6999,
    description: "Budget-friendly durable men's formal dress shoe with a polished synthetic leather upper, reinforced heel counter, and non-slip rubber sole for daily professional work wear.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "Brown"],
  },
  {
    productCode: "BT-057",
    name: "Bata Formal Slip-On Moccasin",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 9200,
    salePrice: null,
    description: "Comfortable formal slip-on moccasin designed for office commuters. Features a padded collar, memory foam sockliner, and flexible textured outsole.",
    imageUrl: IMAGES.menLoafer,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black", "Coffee Brown"],
  },
  {
    productCode: "CL-058",
    name: "Clarks Batcombe Lord Leather Chelsea Boot",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 29500,
    salePrice: 25900,
    isNew: true,
    description: "Premium men's Chelsea boot in dark brown oiled leather. Features dual elastic side gores, a Goodyear welted construction, and a cleated rubber commando sole for winter style.",
    imageUrl: IMAGES.menChelseaBoot,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Dark Brown", "Black"],
  },
  {
    productCode: "TB-059",
    name: "Timberland 6-Inch Premium Waterproof Boot",
    brandName: "Timberland",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 38500,
    salePrice: null,
    isFeatured: true,
    description: "Iconic waterproof nubuck leather work and outdoor boot. Built with seam-sealed construction, 400g PrimaLoft insulation, and rugged rubber lug outsole for all-weather traction.",
    imageUrl: IMAGES.menHikingBoot,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Wheat Nubuck", "Black", "Rust"],
  },
  {
    productCode: "TB-060",
    name: "Timberland Bradstreet Chukka Leather Boot",
    brandName: "Timberland",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 27000,
    salePrice: 22500,
    description: "Modern smart-casual chukka boot featuring SensorFlex comfort system for triple-layer cushioning. Lightweight and versatile for weekend outings and casual Fridays.",
    imageUrl: IMAGES.menChelseaBoot,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Brown", "Navy Suede"],
  },
  {
    productCode: "TB-061",
    name: "Timberland Mt. Maddsen Waterproof Hiking Boot",
    brandName: "Timberland",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 31000,
    salePrice: 27900,
    description: "Trail-ready men's waterproof hiking boot with anti-fatigue comfort technology, fully gusseted tongue to keep debris out, and internal TPU shank for torsional rigidity on rugged terrain.",
    imageUrl: IMAGES.menHikingBoot,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Medium Brown", "Dark Grey"],
  },
  {
    productCode: "HP-062",
    name: "Hush Puppies Expert Suede Driving Moccasin",
    brandName: "Hush Puppies",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 15500,
    salePrice: 12900,
    description: "Ultra-soft suede driving shoe with traditional pebbled rubber sole extending up the heel. Provides supreme flexibility and barefoot comfort for weekend leisure.",
    imageUrl: IMAGES.menLoafer,
    sizes: [39, 40, 41, 42, 43],
    colors: ["Navy", "Olive Suede", "Tan"],
  },
  {
    productCode: "VN-063",
    name: "Vans Classic Slip-On Core",
    brandName: "Vans",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 12500,
    salePrice: 9999,
    isFeatured: true,
    description: "Iconic low-profile canvas slip-on shoe with elastic side accents and signature rubber waffle outsole. Effortless everyday casual footwear for university, streets, and casual hangouts.",
    imageUrl: IMAGES.menSlipOn,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Black / White Checkerboard", "Solid Black", "True White"],
  },
  {
    productCode: "VN-064",
    name: "Vans Old Skool Suede Canvas Sneaker",
    brandName: "Vans",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 14000,
    salePrice: 11900,
    description: "Heritage low-top skate shoe featuring the iconic side stripe, reinforced toe caps to withstand repeated wear, and padded collars for support and flexibility.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black / White", "Navy", "Racing Red"],
  },
  {
    productCode: "CV-065",
    name: "Converse Chuck Taylor All Star Classic High Top",
    brandName: "Converse",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 13500,
    salePrice: 11500,
    isFeatured: true,
    description: "The definitive canvas basketball sneaker turned cultural icon. Features lightweight canvas upper, star ankle patch, and vulcanized rubber sole for timeless everyday style.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Optical White", "Black", "Navy", "Red"],
  },
  {
    productCode: "CV-066",
    name: "Converse Chuck 70 Vintage Canvas Low",
    brandName: "Converse",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 16500,
    salePrice: null,
    isNew: true,
    description: "Premium vintage edition Chuck 70 crafted with 12oz organic canvas, elevated winged tongue stitching, and extra-cushioned OrthoLite insole for all-day city walking.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Parchment Cream", "Black", "Sunflower Yellow"],
  },
  {
    productCode: "SK-067",
    name: "Skechers GOwalk 6 Men's Daily Commuter",
    brandName: "Skechers",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 18500,
    salePrice: 15900,
    isFeatured: true,
    description: "Comfort walking sneaker engineered with high-rebound Hyper Pillar Technology and Air-Cooled Goga Mat insole. Ideal for commuters and individuals who walk 10 km daily.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Charcoal Grey", "Black", "Navy"],
  },
  {
    productCode: "BT-068",
    name: "Bata Power Energy Men's Walking Jogger",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 7800,
    salePrice: 6200,
    description: "Affordable and lightweight men's daily jogger with a breathable knit mesh upper, cushioned EVA midsole, and reinforced toe bumper for daily university wear.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Grey / Blue", "Black / Red"],
  },

  // 2. WOMEN'S HEELS, PUMPS, FLATS, WEDGES & BOOTS
  {
    productCode: "AL-069",
    name: "Aldo Stessy Pointed Toe Stiletto Pump",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 23500,
    salePrice: 19900,
    isFeatured: true,
    description: "Head-turning women's stiletto heel featuring a sleek 4-inch heel, dramatic pointed toe, and Pillow Walk dual-density foam technology for wedding and gala evenings.",
    imageUrl: IMAGES.womenHeelsStiletto,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Classic Black", "Nude Blush", "Ruby Red"],
  },
  {
    productCode: "AL-070",
    name: "Aldo Cassedy Pointy Toe Office Pump",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 21000,
    salePrice: 17500,
    description: "Chic women's high-heel pump with a polished silhouette, cushioned insole, and slim 3.5-inch heel. The definitive formal office heel for corporate leadership and presentations.",
    imageUrl: IMAGES.womenHeelsStiletto,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black Patent", "Beige Matte", "Navy Blue"],
  },
  {
    productCode: "SM-071",
    name: "Steve Madden Carrson Suede Block Heel Sandal",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 24500,
    salePrice: null,
    isFeatured: true,
    isNew: true,
    description: "Versatile women's block heel sandal with a slender ankle strap and stable 3-inch chunky heel. Provides exceptional balance and comfort for outdoor weddings and parties.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Suede", "Champagne Gold", "Tan Suede"],
  },
  {
    productCode: "SM-072",
    name: "Steve Madden Irenee Low Block Heel Sandal",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 21500,
    salePrice: 18500,
    description: "Comfortable low block heel sandal with a 2-inch heel height and minimalist toe strap. Perfect for university presentations, office wear, and standing comfortably all day.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Blush Pink", "Black", "Silver Metallic"],
  },
  {
    productCode: "AL-073",
    name: "Aldo Dalsie Strappy Platform Evening Heel",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 26500,
    salePrice: 22900,
    isNew: true,
    description: "Dramatic platform high heel with crisscross satin straps and secure buckle closure. Built with a supportive front platform that reduces the perceived heel pitch for dance parties.",
    imageUrl: IMAGES.womenHeelsPlatform,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Emerald Green", "Midnight Black", "Gold Shimmer"],
  },
  {
    productCode: "CL-074",
    name: "Clarks Linvale Jerica Leather Kitten Heel Pump",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 19500,
    salePrice: 16500,
    isFeatured: true,
    description: "Ergonomic women's kitten heel pump featuring a modest 2.2-inch heel and targeted Ultimate Comfort cushioning. Ideal for professionals who require formal heels with zero foot fatigue.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Nude Praline", "Navy Suede"],
  },
  {
    productCode: "CL-075",
    name: "Clarks Willow Sun Cork Wedge Heel Sandal",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 18000,
    salePrice: 14900,
    description: "Summery women's wedge sandal crafted with a lightweight natural cork wedge, soft leather crossbands, and high-density foam padding for warm-weather garden parties and brunches.",
    imageUrl: IMAGES.womenSandalsHeeled,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Tan Leather", "Black", "Coral Red"],
  },
  {
    productCode: "BT-076",
    name: "Bata Comfit Women's Comfort Wedge Heel",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 6500,
    salePrice: 5200,
    description: "Budget-friendly low wedge sandal engineered with Bata Comfit ergonomic arch cushion and elasticated strap for teachers, doctors, and mothers standing on their feet all day.",
    imageUrl: IMAGES.womenSandalsHeeled,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Beige", "Black", "Maroon"],
  },
  {
    productCode: "BT-077",
    name: "Bata Marie Claire Block Heel Court Shoe",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 7500,
    salePrice: 5999,
    description: "Affordable women's formal court shoe featuring a mid block heel, rounded toe box, and soft cushioned insole for daily office and university wear.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black", "Brown", "Burgundy"],
  },
  {
    productCode: "AL-078",
    name: "Aldo Abaerith Pointed Leather Ballet Flat",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 16500,
    salePrice: 13900,
    isFeatured: true,
    description: "Sleek pointed-toe leather flat shoe with a micro-heel and Pillow Walk cushioning. Sophisticated and minimalist alternative to heels for work, travel, and formal dinners.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black", "Cream White", "Cognac Tan"],
  },
  {
    productCode: "SM-079",
    name: "Steve Madden Feather Leather Loafer Flat",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 18500,
    salePrice: null,
    isNew: true,
    description: "Ultra-flexible women's flat loafer featuring a notched topline, pointed toe, and buttery soft leather that molds naturally to the foot for everyday casual sophistication.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Bone Cream", "Black Leather", "Snake Print"],
  },
  {
    productCode: "CL-080",
    name: "Clarks Pure Tone Slip-On Leather Mule Flat",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 22000,
    salePrice: 18900,
    description: "Luxurious slip-on mule flat that transitions effortlessly from work to casual weekends. Features a collapsible heel back and breathable sheepskin sockliner.",
    imageUrl: IMAGES.womenFlatsMules,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Nude Suede", "Sage Green"],
  },
  {
    productCode: "BT-081",
    name: "Bata Marie Claire Everyday Bow Ballet Flat",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 5500,
    salePrice: 4800,
    description: "Cute and comfortable everyday women's ballet flat with a delicate bow accent, elasticized collar for a snug fit, and anti-slip rubber outsole for university and shopping.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black", "Blush Pink", "Navy Blue"],
  },
  {
    productCode: "SM-082",
    name: "Steve Madden Latch Lug-Sole Chelsea Ankle Boot",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 28500,
    salePrice: 24500,
    isFeatured: true,
    isNew: true,
    description: "Edgy women's Chelsea ankle boot featuring a chunky cleated lug sole, high elastic stretch panels, and durable leather upper for bold street style and winter warmth.",
    imageUrl: IMAGES.womenBootsChelsea,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Off-White Cream"],
  },
  {
    productCode: "AL-083",
    name: "Aldo Bigpoint Suede Block Heel Ankle Boot",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 26000,
    salePrice: 21900,
    description: "Refined women's ankle boot crafted in velvety suede with an almond toe, inner side zipper, and sturdy 3-inch stacked block heel for autumn and winter outfits.",
    imageUrl: IMAGES.womenBootsAnkle,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Cognac Suede", "Black Suede", "Olive"],
  },
  {
    productCode: "TB-084",
    name: "Timberland Courmayeur Valley Women's Winter Boot",
    brandName: "Timberland",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 34000,
    salePrice: null,
    description: "Italian-styled women's leather boot featuring cozy wool-cotton herringbone lining, lightweight EVA midsole, and rugged traction lugs for cold-weather travels.",
    imageUrl: IMAGES.womenBootsChelsea,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Taupe Suede", "Black Nubuck"],
  },
  {
    productCode: "SK-085",
    name: "Skechers Arch Fit Women's Ultra Walking Shoe",
    brandName: "Skechers",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 19500,
    salePrice: 16900,
    isFeatured: true,
    description: "Podiatrist-certified arch support walking sneaker for women. Features a removable Arch Fit insole system, lightweight responsive ULTRA GO cushioning, and machine-washable mesh upper.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black / Rose Gold", "Navy / Pink", "All White"],
  },
  {
    productCode: "SK-086",
    name: "Skechers D'Lites Fresh Start Chunky Sneaker",
    brandName: "Skechers",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 17500,
    salePrice: 14500,
    description: "Iconic women's retro chunky sneaker with smooth leather and synthetic overlays, air-cooled memory foam cushioned insole, and thick shock-absorbing midsole.",
    imageUrl: IMAGES.womenCasualSneaker,
    sizes: [36, 37, 38, 39, 40],
    colors: ["White / Silver", "Black / White"],
  },
  {
    productCode: "AL-087",
    name: "Aldo Cadalise Flat Leather Slide Sandal",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 14500,
    salePrice: 11900,
    description: "Effortless summer slide sandal featuring interwoven leather straps and a cushioned footbed. Perfect for vacations, beach resorts, and hot summer days.",
    imageUrl: IMAGES.womenSandalsHeeled,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Cognac Brown", "Black", "White"],
  },

  // 3. SPORTS, FOOTBALL, BASKETBALL, TENNIS & TRAINING
  {
    productCode: "NK-088",
    name: "Nike Mercurial Superfly 9 Academy Football Cleats",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 28500,
    salePrice: 24900,
    isFeatured: true,
    isNew: true,
    description: "High-performance football / soccer boots featuring a Zoom Air unit for explosive propulsive speed on firm ground natural grass and artificial turf pitches.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Volt Yellow", "Bright Crimson / Black", "Metallic Silver"],
  },
  {
    productCode: "AD-089",
    name: "Adidas Predator Accuracy.3 Firm Ground Soccer Shoes",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 26000,
    salePrice: null,
    isFeatured: true,
    description: "Control-focused football boots with High Definition 3D grip texture across the strike zone for pinpoint passing, curve, and powerful shooting.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Core Black / White / Team Shock Pink", "Cloud White / Lucid Lemon"],
  },
  {
    productCode: "PM-090",
    name: "Puma Future Match Indoor Futsal Shoes",
    brandName: "Puma",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 19500,
    salePrice: 16500,
    description: "Indoor football and futsal shoe engineered with FUZIONFIT adaptive compression band and non-marking low-profile gum rubber outsole for tight court grip.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Puma White / Fire Orchid", "Blue Glimmer"],
  },
  {
    productCode: "NK-091",
    name: "Nike Giannis Immortality 3 Basketball Shoes",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 25000,
    salePrice: 21500,
    isFeatured: true,
    description: "Dynamic basketball shoe built for intense court mobility. Features curved foam cushioning from heel to toe for smooth strides and oversized herringbone traction grooves.",
    imageUrl: IMAGES.sportsBasketball,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black / White / University Red", "White / Deep Royal Blue"],
  },
  {
    productCode: "AD-092",
    name: "Adidas Barricade Tennis Hard Court Shoes",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 32000,
    salePrice: null,
    isNew: true,
    description: "Tournament-grade tennis shoe featuring Geofit Sensepods for locked-in heel support, Bounce midsole for energetic returns, and durable Adiwear 6 court outsole.",
    imageUrl: IMAGES.sportsTennis,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Core Black / Solar Red", "Cloud White / Silver Metallic"],
  },
  {
    productCode: "AS-093",
    name: "ASICS Gel-Resolution 9 Hardcourt Tennis Shoe",
    brandName: "ASICS",
    categoryName: "Sports",
    gender: ProductGender.Women,
    basePrice: 33500,
    salePrice: 29900,
    isFeatured: true,
    description: "Premium women's tennis shoe with DYNAWALL technology for enhanced lateral stability and rearfoot/forefoot GEL cushioning for harsh deceleration shock absorption.",
    imageUrl: IMAGES.sportsTennis,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["White / Amethyst Purple", "Safety Yellow / Black"],
  },
  {
    productCode: "AS-094",
    name: "ASICS Gel-Trabuco 11 Trail Running Shoes",
    brandName: "ASICS",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 31500,
    salePrice: 26900,
    description: "Rugged off-road trail running shoe featuring ASICSGRIP aggressive rubber lugs, flexible rock protection plate, and lightweight FF BLAST cushioning for muddy wilderness hikes.",
    imageUrl: IMAGES.sportsTrailRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black / Electric Red", "Olive Canvas"],
  },
  {
    productCode: "RB-095",
    name: "Reebok Nano X3 Cross-Training Gym Shoe",
    brandName: "Reebok",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 27500,
    salePrice: 23900,
    isFeatured: true,
    description: "The ultimate gym workout shoe featuring the innovative Lift and Run Chassis system that stiffens during heavy squats and deadlifts while remaining flexible during sprints.",
    imageUrl: IMAGES.sportsGymTraining,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Core Black / Footwear White", "Vector Navy / Orange"],
  },
  {
    productCode: "RB-096",
    name: "Reebok Nano X3 Women's Studio Training Shoes",
    brandName: "Reebok",
    categoryName: "Sports",
    gender: ProductGender.Women,
    basePrice: 27500,
    salePrice: 23900,
    description: "High-performance women's workout and HIIT shoe with Floatride Energy Foam cushioning and all-surface rubber traction for weightlifting, jumping, and cardio classes.",
    imageUrl: IMAGES.sportsGymTraining,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Stucco / Rose Gold", "Chalk White / Black"],
  },
  {
    productCode: "NK-097",
    name: "Nike Offcourt Sport Recovery Slide",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Unisex,
    basePrice: 8500,
    salePrice: 6999,
    description: "Premium post-workout recovery slide engineered with dual-density Revive Foam, soft jersey lining, and deep flex grooves for tired feet after matches and gym sessions.",
    imageUrl: IMAGES.sportsSlides,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Black / White", "Anthracite Grey"],
  },
  {
    productCode: "AD-098",
    name: "Adidas Adilette Comfort Sports Slide",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Unisex,
    basePrice: 8000,
    salePrice: 6499,
    description: "Iconic contoured slide sandal featuring an ultra-soft Cloudfoam Plus footbed for recharging energy after sports training or poolside relaxation.",
    imageUrl: IMAGES.sportsSlides,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Core Black / Cloud White", "Dark Blue / White"],
  },

  // 4. KIDS & CHILDREN
  {
    productCode: "BT-099",
    name: "Bata Smart Boys Leather School Shoes",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Kids,
    basePrice: 5800,
    salePrice: 4999,
    isFeatured: true,
    description: "High-durability all-black boys leather school shoe with scuff-resistant toe cap, reinforced double stitching, and easy velcro closure for active school days.",
    imageUrl: IMAGES.kidsSchoolBoys,
    sizes: [36, 37, 38, 39],
    colors: ["Solid Black"],
  },
  {
    productCode: "BT-100",
    name: "Bata Marie Claire Girls Mary Jane School Shoes",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Kids,
    basePrice: 5500,
    salePrice: 4700,
    isFeatured: true,
    description: "Classic black Mary Jane girls school shoes crafted with polished leather, breathable antibacterial lining, and a flexible non-marking rubber sole.",
    imageUrl: IMAGES.kidsSchoolGirls,
    sizes: [36, 37, 38, 39],
    colors: ["Black"],
  },
  {
    productCode: "SK-101",
    name: "Skechers Microspec Boys Lightweight Running Shoes",
    brandName: "Skechers",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 11500,
    salePrice: 9500,
    isNew: true,
    description: "Lightweight kids sports sneaker with breathable athletic mesh upper, stretch lace front with adjustable instep strap, and shock-absorbing midsole for gym and sports day.",
    imageUrl: IMAGES.kidsSports,
    sizes: [36, 37, 38, 39],
    colors: ["Navy / Orange", "Black / Lime"],
  },
  {
    productCode: "SK-102",
    name: "Skechers Sparkle Lite Girls Casual Party Sneakers",
    brandName: "Skechers",
    categoryName: "Women",
    gender: ProductGender.Kids,
    basePrice: 12500,
    salePrice: 10500,
    description: "Fun and sparkly girls casual sneaker with canvas glitter finish, memory foam cushioned comfort insole, and easy slip-on fit for parties and everyday casual wear.",
    imageUrl: IMAGES.kidsSneakers,
    sizes: [36, 37, 38, 39],
    colors: ["Pink / Multi-Glitter", "Lavender / Silver"],
  },
  {
    productCode: "NK-103",
    name: "Nike Jr. Mercurial Vapor 15 Kids Football Boots",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 17500,
    salePrice: 14900,
    description: "Youth football cleats designed for speed and acceleration on natural and artificial grass pitches with molded studs and textured synthetic upper.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [36, 37, 38, 39],
    colors: ["Metallic Copper", "Bright Yellow"],
  },
  {
    productCode: "AD-104",
    name: "Adidas FortaRun Kids Everyday Running Shoes",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 13500,
    salePrice: 11200,
    description: "Versatile unisex kids running shoes made with recycled materials, Cloudfoam soft midsole, and durable rubber outsole for school games and playground sports.",
    imageUrl: IMAGES.kidsSports,
    sizes: [36, 37, 38, 39],
    colors: ["Core Black / White", "Royal Blue / Silver"],
  },

  // 5. ADDITIONAL CASUAL, OFFICE, RUNNING & WEDDING ITEMS
  {
    productCode: "CL-105",
    name: "Clarks Tilden Free Leather Slip-On",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 18900,
    salePrice: 15900,
    description: "Sleek professional slip-on shoe with stretch gore panels and high-cushion footbed for busy executives and daily office wear.",
    imageUrl: IMAGES.menLoafer,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "Dark Tan"],
  },
  {
    productCode: "CL-106",
    name: "Clarks Desert Boot in Beeswax Leather",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 28000,
    salePrice: null,
    isFeatured: true,
    description: "The timeless 1950s icon crafted with rich beeswax leather and natural crepe sole. The quintessential smart-casual boot for chinos and denim.",
    imageUrl: IMAGES.menChelseaBoot,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Beeswax Brown", "Sand Suede"],
  },
  {
    productCode: "HP-107",
    name: "Hush Puppies Heath Leather Casual Sneaker",
    brandName: "Hush Puppies",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 16500,
    salePrice: 13900,
    description: "Minimalist full-grain leather sneaker designed for casual office days and weekend city walks with BioBevel heel support.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["White Leather", "Navy", "Cognac"],
  },
  {
    productCode: "BT-108",
    name: "Bata Weinbrenner Rugged Outdoor Boot",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 11500,
    salePrice: 9999,
    description: "Heavy-duty outdoor ankle boot featuring water-resistant oil pull-up leather, padded collar, and deep-tread rubber sole for hiking and trail walks.",
    imageUrl: IMAGES.menHikingBoot,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Tan Oiled", "Dark Brown"],
  },
  {
    productCode: "BT-109",
    name: "Bata Safari Suede Desert Chukka",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 8900,
    salePrice: 7500,
    description: "Classic budget suede chukka boot with stitch-down sole construction. Lightweight, breathable, and versatile for university students.",
    imageUrl: IMAGES.menChelseaBoot,
    sizes: [39, 40, 41, 42, 43],
    colors: ["Sand Suede", "Chocolate Brown"],
  },
  {
    productCode: "VN-110",
    name: "Vans Era Classic Canvas Skateboard Shoes",
    brandName: "Vans",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 12000,
    salePrice: null,
    description: "Classic lace-up low-top shoe featuring sturdy double-stitched canvas uppers, metal eyelets, and signature rubber waffle outsoles.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Navy / Canvas", "Black / Classic", "Burgundy"],
  },
  {
    productCode: "CV-111",
    name: "Converse One Star Pro Suede Low Top",
    brandName: "Converse",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 15500,
    salePrice: 12900,
    description: "Durable vintage suede low top sneaker with CX foam cushioning for impact absorption and die-cut star logo for retro street credibility.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black / White Suede", "Sage Green Suede"],
  },
  {
    productCode: "SK-112",
    name: "Skechers Equalizer 4.0 Relaxed Fit Slip-On",
    brandName: "Skechers",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 16000,
    salePrice: 13500,
    description: "Relaxed Fit roomier toe box walking shoe with soft knit mesh fabric and Air-Cooled Memory Foam insole for broad or wide feet comfort.",
    imageUrl: IMAGES.menSlipOn,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "Charcoal"],
  },
  {
    productCode: "NB-113",
    name: "New Balance 574 Core Heritage Sneaker",
    brandName: "New Balance",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 23500,
    salePrice: 19900,
    isFeatured: true,
    description: "The most iconic New Balance sneaker combining suede and mesh uppers with ENCAP midsole cushioning for timeless casual style and all-day walking support.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Grey / White", "Navy Blue", "Burgundy"],
  },
  {
    productCode: "NB-114",
    name: "New Balance 990v5 Made in USA Premium Trainer",
    brandName: "New Balance",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 44000,
    salePrice: null,
    isFeatured: true,
    isNew: true,
    description: "Top-tier premium lifestyle running shoe featuring pigskin leather overlays, dual-density collar foam, and Ortholite insert for peerless comfort and standing all day.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Classic Castlerock Grey", "Triple Black"],
  },
  {
    productCode: "PM-115",
    name: "Puma Smash v2 Leather Casual Sneaker",
    brandName: "Puma",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 13500,
    salePrice: 10900,
    description: "Tennis-inspired clean leather trainer with soft suede Formstrip overlay and SoftFoam+ comfort sockliner for easy everyday pairing with jeans.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Puma White / Black", "All Black"],
  },
  {
    productCode: "AD-116",
    name: "Adidas Stan Smith Sustainable Leather Sneaker",
    brandName: "Adidas",
    categoryName: "Men",
    gender: ProductGender.Unisex,
    basePrice: 21000,
    salePrice: 17900,
    isFeatured: true,
    description: "Crisp white minimalist leather court sneaker with perforated 3-Stripes and green heel tab. The gold standard for clean casual university and office footwear.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Cloud White / Fairway Green", "Cloud White / Collegiate Navy"],
  },
  {
    productCode: "AL-117",
    name: "Aldo Cerquefuglietta Slingback Block Heel",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 22500,
    salePrice: 18900,
    description: "Feminine slingback pump featuring a modern square toe, sculpted 2.5-inch block heel, and adjustable heel strap for comfortable business elegance.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black Gloss", "Ivory Cream", "Pastel Blue"],
  },
  {
    productCode: "AL-118",
    name: "Aldo Loverly Ankle Strap Stiletto Heel",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 24000,
    salePrice: null,
    isNew: true,
    description: "Dazzling high-heel evening sandal with rhinestone embellishments across the delicate toe strap. Essential footwear for wedding guest and cocktail dresses.",
    imageUrl: IMAGES.womenHeelsStiletto,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Silver Crystal", "Rose Gold", "Jet Black"],
  },
  {
    productCode: "SM-119",
    name: "Steve Madden Daisie Classic Pointy Pump",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 23000,
    salePrice: 19500,
    description: "Statuesque 4-inch stiletto pump with perfectly proportioned pointy toe and synthetic lining. A must-have power heel for formal corporate and evening wear.",
    imageUrl: IMAGES.womenHeelsStiletto,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Red Patent", "Black Leather", "Nude Blush"],
  },
  {
    productCode: "SM-120",
    name: "Steve Madden Viviana Chunky Platform Mule",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 25000,
    salePrice: 21000,
    description: "Retro 70s-inspired platform mule featuring a bold wooden-look block heel and wide soft strap for effortless high-fashion summer styling.",
    imageUrl: IMAGES.womenHeelsPlatform,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Cognac Leather", "Black"],
  },
  {
    productCode: "CL-121",
    name: "Clarks Juliet Palm Leather Loafer Heel",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 19000,
    salePrice: 15900,
    description: "Sophisticated low stacked heel loafer in rich leather with decorative metal bit hardware. Provides unparalleled underfoot cushioning for teachers and executives.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Burgundy Croc", "Navy"],
  },
  {
    productCode: "CL-122",
    name: "Clarks Sheer Rose Slingback Pointed Court",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 21000,
    salePrice: 17900,
    description: "Graceful pointed-toe slingback court shoe with a 2.5-inch block heel, full leather sockliner, and targeted arch foam for day-to-night comfort.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Praline Nude", "Black Patent"],
  },
  {
    productCode: "BT-123",
    name: "Bata Marie Claire Block Heel Sandal",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 6200,
    salePrice: 5200,
    description: "Budget women's party sandal with a supportive 2.5-inch block heel, shimmery cross straps, and buckle fastening for family dinners and festive occasions.",
    imageUrl: IMAGES.womenSandalsHeeled,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Golden Champagne", "Silver", "Black"],
  },
  {
    productCode: "BT-124",
    name: "Bata Formal Pointed Kitten Heel",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 6800,
    salePrice: 5799,
    description: "Smart low-heel pump with a modest 1.8-inch kitten heel and cushioned interior. Affordable professional choice for office workers and university students.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black", "Mocha Brown"],
  },
  {
    productCode: "SM-125",
    name: "Steve Madden Donddi Flat Leather Sandal",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 15500,
    salePrice: 12900,
    description: "Minimalist flat sandal with thick leather crossover straps, ankle strap with buckle, and a durable micro-heel for laid-back weekend summer strolls.",
    imageUrl: IMAGES.womenSandalsHeeled,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Tan Leather", "Black Leather", "White"],
  },
  {
    productCode: "AL-126",
    name: "Aldo Braylynn Pointed Toe D'Orsay Flat",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 17500,
    salePrice: 14500,
    description: "Elegant two-piece d'Orsay flat with side cutouts, pointed toe silhouette, and Pillow Walk insole. Refined alternative to formal heels for long events.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black Micro-Suede", "Leopard Print", "Blush Pink"],
  },
  {
    productCode: "CL-127",
    name: "Clarks Un Darcey Bow Leather Ballet Flat",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 20500,
    salePrice: 17500,
    description: "Part of the Clarks Unstructured collection: ultra-lightweight leather ballet flat with perforated breathable lining and arch support for standing all day.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Aubergine Plum", "Navy"],
  },
  {
    productCode: "BT-128",
    name: "Bata Comfit Soft Leather Flat Loafer",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 5900,
    salePrice: 4999,
    description: "Ultra-soft flexible moccasin flat with padded heel counter and shock-absorbing textured rubber sole. Designed specifically for mothers and daily errands.",
    imageUrl: IMAGES.womenFlatsBallet,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Beige", "Black", "Tan"],
  },
  {
    productCode: "SM-129",
    name: "Steve Madden Howler Suede Ankle Boot",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 27500,
    salePrice: 23500,
    isFeatured: true,
    description: "Trendy platform Chelsea ankle boot with high-traction cleated outsole, elastic gores, and rear pull tab for chic cold-weather streetwear outfits.",
    imageUrl: IMAGES.womenBootsChelsea,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Chestnut Brown Suede", "Black Leather"],
  },
  {
    productCode: "AL-130",
    name: "Aldo Reilly Knee-High Leather Riding Boot",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 38000,
    salePrice: null,
    isNew: true,
    description: "Stunning tall knee-high equestrian boot in smooth leather with full inside zipper, subtle metallic buckle, and low stacked heel for autumn and winter luxury.",
    imageUrl: IMAGES.womenBootsAnkle,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Deep Espresso Brown", "Onyx Black"],
  },
  {
    productCode: "TB-131",
    name: "Timberland Nellie Waterproof Women's Chukka",
    brandName: "Timberland",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 32500,
    salePrice: 27900,
    description: "Low-profile women's waterproof nubuck ankle boot with anti-fatigue comfort technology, padded collar, and durable lug outsole for outdoor and rainy weather.",
    imageUrl: IMAGES.womenBootsChelsea,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Wheat Nubuck", "Dark Grey"],
  },
  {
    productCode: "SK-132",
    name: "Skechers GO WALK Joy Women's Slip-On Jogger",
    brandName: "Skechers",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 17000,
    salePrice: 14500,
    isFeatured: true,
    description: "Featherlight slip-on walking shoe with innovative 5GEN midsole design, breathable athletic mesh, and Goga Max high-rebound insole for walking 10 km daily.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black / White", "Taupe", "Charcoal Pink"],
  },
  {
    productCode: "NK-133",
    name: "Nike Court Legacy Lift Women's Platform Sneaker",
    brandName: "Nike",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 24000,
    salePrice: 19900,
    description: "Fashion-forward platform sneaker featuring crisp leather construction, elevated midsole, and herringbone rubber outsole for everyday university styling.",
    imageUrl: IMAGES.womenCasualSneaker,
    sizes: [36, 37, 38, 39, 40],
    colors: ["White / Black", "Sail / Hemp"],
  },
  {
    productCode: "AD-134",
    name: "Adidas Cloudfoam Pure 2.0 Women's Runners",
    brandName: "Adidas",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 16500,
    salePrice: 13900,
    description: "Sleek women's slip-on running-inspired sneaker crafted with Primegreen recycled materials and plush Cloudfoam memory sockliner for all-day errands.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Core Black / White", "Grey Two / Halo Silver", "Wonder Mauve"],
  },
  {
    productCode: "PM-135",
    name: "Puma Ultra Match Firm Ground Football Boots",
    brandName: "Puma",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 25500,
    salePrice: 21900,
    description: "Ultra-lightweight speed football cleats with GripControl skin for decisive ball mastery and TPU Speedplate outsole for quick burst acceleration.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Ultra Blue / White", "Poison Pink"],
  },
  {
    productCode: "NK-136",
    name: "Nike Tiempo Legend 10 Academy Turf Football Shoes",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 23500,
    salePrice: null,
    isNew: true,
    description: "Engineered leather turf football boots with micro-dots that amplify touch zones for shooting, dribbling, and passing on artificial turf courts.",
    imageUrl: IMAGES.sportsFootball,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black / Chrome", "White / Bright Crimson"],
  },
  {
    productCode: "AD-137",
    name: "Adidas Dame 8 EXTPLY Basketball High Tops",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 29000,
    salePrice: 24500,
    description: "Signature basketball sneaker engineered with dual-density Bounce Pro cushioning for explosive drives, hard landings, and supreme ankle stability.",
    imageUrl: IMAGES.sportsBasketball,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Core Black / Gold Metallic", "Signal Cyan"],
  },
  {
    productCode: "AS-138",
    name: "ASICS Gel-Rocket 11 Indoor Court Shoes",
    brandName: "ASICS",
    categoryName: "Sports",
    gender: ProductGender.Unisex,
    basePrice: 19500,
    salePrice: 16500,
    isFeatured: true,
    description: "Multi-purpose indoor court shoe for badminton, volleyball, and squash. Features forefoot GEL technology and TRUSSTIC system to prevent twisting on sudden cuts.",
    imageUrl: IMAGES.sportsTennis,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["White / Directoire Blue", "Black / Safety Yellow"],
  },
  {
    productCode: "NK-139",
    name: "Nike Air Zoom Structure 25 Stability Runners",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 33000,
    salePrice: 28900,
    isFeatured: true,
    description: "Premium stability running shoes engineered for runners needing arch support and pronation control. Packed with Cushlon 3.0 foam and Zoom Air unit.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black / Pure Platinum", "Geode Teal"],
  },
  {
    productCode: "AD-140",
    name: "Adidas Terrex Free Hiker 2.0 Gore-Tex Trail Shoes",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 42000,
    salePrice: null,
    isNew: true,
    description: "Waterproof Gore-Tex trail hiking sneaker combining responsive Boost midsole with Continental Rubber tire grip for long-distance mountain trekking.",
    imageUrl: IMAGES.sportsTrailRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Core Black / Carbon", "Wonder Steel"],
  },
  {
    productCode: "AS-141",
    name: "ASICS GT-2000 12 Women's Overpronation Running Shoe",
    brandName: "ASICS",
    categoryName: "Sports",
    gender: ProductGender.Women,
    basePrice: 34500,
    salePrice: 29900,
    isFeatured: true,
    description: "Targeted stability running shoe featuring 3D GUIDANCE SYSTEM for balanced transitions, PureGEL rearfoot cushioning, and lightweight FF BLAST PLUS foam.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black / Lilac Hint", "Illuminate Mint"],
  },
  {
    productCode: "RB-142",
    name: "Reebok Lifter PR III Weightlifting Shoes",
    brandName: "Reebok",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 29500,
    salePrice: 25900,
    description: "Dedicated Olympic weightlifting and powerlifting shoe with raised solid TPU heel wedge, midfoot lock-down strap, and flat anti-slip rubber outsole for maximum drive.",
    imageUrl: IMAGES.sportsGymTraining,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Core Black / Cold Grey", "White / Black"],
  },
  {
    productCode: "PM-143",
    name: "Puma Fuse 2.0 High-Intensity Training Shoes",
    brandName: "Puma",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 22000,
    salePrice: 18500,
    description: "Zero-drop cross-training shoe with PUMAGRIP rubber compound, wide toe box for natural splay during heavy lifts, and TPU heel clip for handstand push-up stability.",
    imageUrl: IMAGES.sportsGymTraining,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Puma Black / Lime Squeeze", "Cool Dark Grey"],
  },
  {
    productCode: "SK-144",
    name: "Skechers Max Cushioning Premier Trail Runners",
    brandName: "Skechers",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 23500,
    salePrice: 19500,
    description: "Max-cushioned trail runner with Goodyear rubber all-terrain traction, ULTRA GO responsive platform, and water-repellent treated mesh for rough gravel hikes.",
    imageUrl: IMAGES.sportsTrailRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Charcoal / Orange", "Black / Blue"],
  },
  {
    productCode: "BT-145",
    name: "Bata Junior Active Boys Football Cleats",
    brandName: "Bata",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 6500,
    salePrice: 5400,
    description: "Affordable youth football cleats with durable synthetic upper, padded ankle collar, and molded plastic studs for school football leagues.",
    imageUrl: IMAGES.kidsSports,
    sizes: [36, 37, 38, 39],
    colors: ["Black / Neon Green", "Royal Blue / Orange"],
  },
  {
    productCode: "BT-146",
    name: "Bata Princess Glitter Party Shoes for Girls",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Kids,
    basePrice: 4800,
    salePrice: 3999,
    description: "Delightful girls party flat with glitter texture, rhinestone bow accent, and soft cushioned insole for birthdays, weddings, and celebrations.",
    imageUrl: IMAGES.kidsSchoolGirls,
    sizes: [36, 37, 38, 39],
    colors: ["Silver Glitter", "Gold", "Baby Pink"],
  },
  {
    productCode: "SK-147",
    name: "Skechers Go Run 650 Boys Athletic Sneakers",
    brandName: "Skechers",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 12000,
    salePrice: 9999,
    description: "Breathable kids slip-on sneaker with stretch laces and velcro strap, cushioned comfort insole, and shock-absorbing midsole for daily PE classes.",
    imageUrl: IMAGES.kidsSports,
    sizes: [36, 37, 38, 39],
    colors: ["Black / Royal Blue", "Red / Black"],
  },
  {
    productCode: "NK-148",
    name: "Nike Revolution 6 Kids Hook-and-Loop Running Shoes",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 15500,
    salePrice: 12900,
    isFeatured: true,
    description: "Versatile lightweight running shoes for kids made with 20% recycled material, soft foam underfoot, and a full-length rubber outsole for playground games.",
    imageUrl: IMAGES.kidsSports,
    sizes: [36, 37, 38, 39],
    colors: ["Black / Hyper Royal", "Smoke Grey / Sunset"],
  },
  {
    productCode: "AD-149",
    name: "Adidas Tensaur Sport 2.0 Kids School Shoes",
    brandName: "Adidas",
    categoryName: "Men",
    gender: ProductGender.Kids,
    basePrice: 14000,
    salePrice: 11900,
    description: "All-black durable synthetic leather kids school and everyday sneakers with hook-and-loop straps and non-marking rubber outsole.",
    imageUrl: IMAGES.kidsSchoolBoys,
    sizes: [36, 37, 38, 39],
    colors: ["Core Black / Core Black"],
  },
  {
    productCode: "PM-150",
    name: "Puma Evolve Slip-On Kids Casual Shoes",
    brandName: "Puma",
    categoryName: "Sports",
    gender: ProductGender.Kids,
    basePrice: 11000,
    salePrice: 8999,
    description: "Comfortable pull-on kids slip-on with dynamic webbing loops, EVA cushioned footbed, and flexible outsole for energetic children on the move.",
    imageUrl: IMAGES.kidsSneakers,
    sizes: [36, 37, 38, 39],
    colors: ["Puma Black / White", "Elektro Purple"],
  },
  {
    productCode: "CL-151",
    name: "Clarks Bradley Vibe Men's Lightweight Casual Oxford",
    brandName: "Clarks",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 20500,
    salePrice: 17500,
    description: "Hybrid smart-casual shoe pairing tumbled leather with an ultra-lightweight EVA sole. Effortless office and casual weekend crossover.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black Tumbled", "Brown Oiled Leather"],
  },
  {
    productCode: "HP-152",
    name: "Hush Puppies Leverage Waterproof Dress Oxford",
    brandName: "Hush Puppies",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 23500,
    salePrice: 19900,
    description: "WeatherSMART waterproof leather formal oxford with seam-sealed construction, padded collar, and Gel Heel pad for rain-ready boardroom elegance.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black Waterproof", "Brown Waterproof"],
  },
  {
    productCode: "AL-153",
    name: "Aldo Grandstep Men's Leather Penny Loafer",
    brandName: "Aldo",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 22000,
    salePrice: 18500,
    description: "Modern almond-toe penny loafer crafted from glossy polished leather with Pillow Walk flex technology for weddings and summer parties.",
    imageUrl: IMAGES.menLoafer,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Cognac", "Black Gloss"],
  },
  {
    productCode: "AL-154",
    name: "Aldo Miraniel Strappy Block Heel Wedding Pump",
    brandName: "Aldo",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 25000,
    salePrice: 21500,
    isFeatured: true,
    description: "Stunning bridal and festive evening block heel sandal with satin strap weave, cushioned ball-of-foot padding, and stable 3.2-inch heel.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Ivory Satin", "Metallic Gold", "Soft Silver"],
  },
  {
    productCode: "SM-155",
    name: "Steve Madden Valante Strappy Kitten Heel Sandal",
    brandName: "Steve Madden",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 21000,
    salePrice: 17900,
    description: "Chic square-toe kitten heel sandal with delicate asymmetric tubular straps and a comfortable 2-inch heel height for dinner dates.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black Leather", "Lipstick Red", "Nude"],
  },
  {
    productCode: "CL-156",
    name: "Clarks Emily Andress Leather Block Heel Pump",
    brandName: "Clarks",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 20000,
    salePrice: 16900,
    description: "Classic rounded-toe block heel pump in rich leather with 2.4-inch heel and targeted Ultimate Comfort foam for all-day office comfort.",
    imageUrl: IMAGES.womenHeelsBlock,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Black Leather", "Navy Leather"],
  },
  {
    productCode: "BT-157",
    name: "Bata Ambassador Pure Leather Men's Oxford",
    brandName: "Bata",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 12500,
    salePrice: 10500,
    description: "Handcrafted full-grain leather oxford with leather lining and polished sole edge for courtrooms, weddings, and formal business.",
    imageUrl: IMAGES.formalMenOxford,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black", "Dark Brown"],
  },
  {
    productCode: "BT-158",
    name: "Bata Red Label Heeled Ankle Boot for Women",
    brandName: "Bata",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 8900,
    salePrice: 7500,
    description: "Stylish winter ankle boot with decorative side zipper, comfortable 2.5-inch block heel, and soft velvet lining for cold evenings.",
    imageUrl: IMAGES.womenBootsAnkle,
    sizes: [36, 37, 38, 39, 40],
    colors: ["Black", "Tan Brown"],
  },
  {
    productCode: "SK-159",
    name: "Skechers Hands Free Slip-ins Max Cushioning",
    brandName: "Skechers",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 24500,
    salePrice: 20900,
    isFeatured: true,
    description: "Touchless Fit slip-on sneaker featuring exclusive Heel Pillow technology, ULTRA GO cushioning, and Natural Rocker Technology for 10 km daily walking.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Navy / Grey", "All Black", "Charcoal"],
  },
  {
    productCode: "SK-160",
    name: "Skechers Hands Free Slip-ins Women's Ultra Flex",
    brandName: "Skechers",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 22000,
    salePrice: 18500,
    isFeatured: true,
    description: "Hands-free slip-on women's comfort sneaker with Stretch Fit engineered knit upper and Air-Cooled Memory Foam insole for mothers and teachers.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Mauve Pink", "Black / Rose Gold", "Off White"],
  },
  {
    productCode: "NK-161",
    name: "Nike Invincible 3 Maximum Cushioning Running Shoe",
    brandName: "Nike",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 39500,
    salePrice: 34500,
    isFeatured: true,
    description: "Maximum cushioning premium running shoe with thick stack of ZoomX foam for ultra-soft impact absorption and joint protection on long marathon training runs.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["White / Black / Bright Crimson", "Thunder Blue"],
  },
  {
    productCode: "AD-162",
    name: "Adidas Adizero Boston 12 Marathon Shoes",
    brandName: "Adidas",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 36000,
    salePrice: 31000,
    isNew: true,
    description: "Mid-to-long-distance tempo running shoe powered by glass-fiber ENERGYRODS 2.0 for limit-pushing propulsion and Lightstrike Pro ultra-light foam.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Lucid Lemon / Core Black", "Cloud White / Wonder Blue"],
  },
  {
    productCode: "AS-163",
    name: "ASICS Gel-Kayano 30 Premium Stability Runners",
    brandName: "ASICS",
    categoryName: "Sports",
    gender: ProductGender.Men,
    basePrice: 38500,
    salePrice: null,
    isFeatured: true,
    description: "The 30th anniversary milestone stability runner with revolutionary 4D GUIDANCE SYSTEM, PureGEL technology, and cloud-like FF BLAST PLUS ECO cushioning.",
    imageUrl: IMAGES.sportsRunning,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Black / Glow Yellow", "Sheet Rock / Pure Silver"],
  },
  {
    productCode: "AS-164",
    name: "ASICS Gel-Nimbus 26 Women's Plush Road Runners",
    brandName: "ASICS",
    categoryName: "Women",
    gender: ProductGender.Women,
    basePrice: 39000,
    salePrice: 33900,
    isFeatured: true,
    description: "The softest women's neutral road running shoe featuring HYBRID ASICSGRIP outsole, plush engineered knit collar, and PureGEL heel cushioning for cloud-soft running.",
    imageUrl: IMAGES.womenWalkingShoe,
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["French Blue / Pure Silver", "Pale Mint / White"],
  },
  {
    productCode: "TB-165",
    name: "Timberland Seneca Bay Leather Oxford Sneaker",
    brandName: "Timberland",
    categoryName: "Men",
    gender: ProductGender.Men,
    basePrice: 24000,
    salePrice: 19900,
    description: "Smart-casual men's oxford sneaker crafted with Better Leather from an eco-conscious tannery, cushioned OrthoLite footbed, and high-traction rubber sole.",
    imageUrl: IMAGES.menCasualSneaker,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Medium Brown", "Wheat Nubuck", "Black"],
  },
];

export const ALL_NEW_PRODUCTS = EXPANDED_PRODUCTS_DATA;
